name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build Linux
        run: go build -o bin/tt
        id: build-linux

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o bin/tt.exe
        id: build-windows

      - name: Prepare Release
        run: |
          mkdir -p dist
          zip -j dist/tt-linux bin/tt
          zip -j dist/tt-windows bin/tt.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          tag_name: ${{ github.ref_name }}
          files: |
            dist/tt-linux
            dist/tt-windows
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
